# Generated by Django 3.1.7 on 2021-02-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_exam', '0002_auto_20210225_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labexam',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
